name: civic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  fl_chart: ^0.70.2
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
   

flutter:
  uses-material-design: true
  assets:
    - assets/